# Default values for scorecards-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: nginx
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

# Backstage
backstage:
  route:
    # set to false for kubernetes
    enabled: false
#  global:
#    dynamic:
#      includes:
#        - dynamic-plugins.default.yaml
#      plugins:
#        - disabled: false
#          package: "@janus-idp/backstage-plugin-orchestrator-backend-dynamic@1.21.0"
#          integrity: sha512-/g7pjYZmKXTalWQTH+L5w1Uu4xvKHe6G7RQd2chhP3Ey2opO+IHtz8TtrLa4fCeWxlrrVpfTI6PiXamTAO4zMg==
#          pluginConfig:
#            orchestrator:
#              dataIndexService:
#                url: http://sonataflow-platform-data-index-service
#              editor:
#                path: https://sandbox.kie.org/swf-chrome-extension/0.32.0
#        - disabled: false
#          package: "@janus-idp/backstage-plugin-orchestrator@1.22.0"
#          integrity: sha512-7CAhoVgI2QTErPzZBHXb7OJp1R9c1qtljCF3I92o1ITrn81/3wy1VLMjVmjYK0QrvAkYM9aH/1izoZ4cayKbRw==
#          pluginConfig:
#            dynamicPlugins:
#              frontend:
#                janus-idp.backstage-plugin-orchestrator:
#                  appIcons:
#                    - importName: OrchestratorIcon
#                      module: OrchestratorPlugin
#                      name: orchestratorIcon
#                  dynamicRoutes:
#                    - importName: OrchestratorPage
#                      menuItem:
#                        icon: orchestratorIcon
#                        text: Orchestrator
#                      module: OrchestratorPlugin
#                      path: /orchestrator
#        - disabled: false
#          package: "https://github.com/redhat-developer/rhdh-plugin-export-backstage-backstage/releases/download/v1.2.0/backstage-plugin-notifications-dynamic-0.2.0.tgz"
#          integrity: sha512-juXCynHPSIYThJHh1ZfR+77kyAtla3vNOl1telUgC402KZCUoAVB+X3H4ZACWGZNvFQ8ySyVc5q/mE1MrCzW0g==
#          pluginConfig:
#            dynamicPlugins:
#              frontend:
#                backstage.plugin-notifications:
#                  dynamicRoutes:
#                    - importName: NotificationsPage
#                      menuItem:
#                        config:
#                          props:
#                            titleCounterEnabled: true
#                            webNotificationsEnabled: false
#                        importName: NotificationsSidebarItem
#                      path: /notifications
#        - disabled: false
#          package: "https://github.com/redhat-developer/rhdh-plugin-export-backstage-backstage/releases/download/v1.2.0/backstage-plugin-notifications-backend-dynamic-0.2.0.tgz"
#          integrity: sha512-QxIkZ7uX8CuCu9EUm8t0T0HOv9KT2AboMBwyr0Xu6Xa1I2U3E59YL5f5NQO9yVpidf+6rlV7qTCvJSn5MAQGnw==
#        - disabled: false
#          package: https://github.com/redhat-developer/rhdh-plugin-export-backstage-backstage/releases/download/v1.2.0/backstage-plugin-signals-dynamic-0.0.5.tgz
#          integrity: sha512-QSDkIYPWjgzcBdt3Gvd7Omq472rMI4oy6x7vLTXVHpIzmWetJalaB6SH8dXxORCFqL6hb3ccJjPsn3rSV8+2Jw==
#          pluginConfig:
#            dynamicPlugins:
#              frontend:
#                backstage.plugin-signals: {}
#        - disabled: false
#          package: https://github.com/redhat-developer/rhdh-plugin-export-backstage-backstage/releases/download/v1.2.0/backstage-plugin-signals-backend-dynamic-0.1.3.tgz
#          integrity: sha512-124+7o/wurgiWkSY5j/80SaauAX/3iVACIm+jR5g09r5QlKfO+GCCNuqhJ8xfbNT+bT6OeyWjPRJMkkjap0u4Q==
  upstream:
    # TODO when setting this to false the secret is still referenced in the rhdh
    # deployment, looks like rhdh-backstage chart doesn't support excluding
    # the postrgres secret part.
    postgresql:
      #enabled: false
      primary:
        resources:
          limits:
            ephemeral-storage: 2Gi
    ingress:
      enabled: true # Use Kubernetes Ingress instead of OpenShift Route
    backstage:
      extraVolumes:
        - name: backstage-locations
          configMap:
            name: backstage-locations
        - name: dynamic-plugins-root
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    # -- Size of the volume that will contain the dynamic plugins. It should be large enough to contain all the plugins.
                    storage: 1Gi
        # Volume that will expose the `dynamic-plugins.yaml` file from the `dynamic-plugins` config map.
        # The `dynamic-plugins` config map is created by the helm chart from the content of the `global.dynamic` field.
        - name: dynamic-plugins
          configMap:
            defaultMode: 420
            name: '{{ printf "%s-dynamic-plugins" .Release.Name }}'
            optional: false
        - name: app-config
          configMap:
            defaultMode: 420
            name: '{{ printf "%s-backstage-app-config" .Release.Name }}'
            optional: false
        # Optional volume that allows exposing the `.npmrc` file (through a `dynamic-plugins-npmrc` secret)
        # to be used when running `npm pack` during the dynamic plugins installation by the initContainer.
        - name: dynamic-plugins-npmrc
          secret:
            defaultMode: 420
            optional: true
            secretName: dynamic-plugins-npmrc
        - name: npmcacache
          emptyDir: {}
      extraVolumeMounts:
        - name: backstage-locations
          mountPath: /opt/backstage/locations
        - mountPath: /opt/app-root/src/.npmrc.dynamic-plugins
          name: dynamic-plugins-npmrc
        - name: dynamic-plugins-root
          mountPath: /opt/app-root/src/dynamic-plugins-root
        - name: app-config
          readOnly: true
          mountPath: /opt/app-root/src/default.app-config.yaml
          subPath: default.app-config.yaml
        - name: dynamic-plugins
          readOnly: true
          mountPath: /opt/app-root/src/dynamic-plugins.yaml
          subPath: dynamic-plugins.yaml
      resources:
        limits:
          memory: 2Gi
          cpu: 1000m
        requests:
          memory: 800Mi
          cpu: 200m
      podSecurityContext: # Vanilla Kubernetes doesn't feature OpenShift default SCCs with dynamic UIDs, adjust accordingly to the deployed image
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      image:
        # use 1.2 till we get the CI working again and publishing upstream
        # versions of the orchestrtor and notification plugins
        repository: rhdh-community/rhdh
        tag: "next-arm64"
      extraEnvVarsSecrets:
        - backstage-backend-auth-secret
      appConfig:
        app:
          baseUrl: http://localhost:9090
        backend:
          auth:
            # for backstage < 1.27 we still need this
            keys:
              - secret: ${BACKEND_SECRET}
            externalAccess:
              - type: static
                options:
                  token: ${BACKEND_SECRET}
                  subject: orchestrator
          baseUrl: http://localhost:9090
          cors:
            origin: http://localhost:9090
        integrations:
          github:
            - host: github.com
              token: "INSERT VALID TOKEN HERE"
        auth:
          environment: development
          providers:
            github:
              development:
                clientId: ${GH_PROVIDER_CLIENT_ID:-provide_gh_provider_client_id_in_backstage_backend_auth_secret}
                clientSecret: ${GH_PROVIDER_SECRET:-provide_gh_provider_secret_in_backstage_backend_auth_secret}
            guest:
              dangerouslyAllowOutsideDevelopment: true
              userEntityRef: user:default/guest
        catalog:
          rules:
            - allow: [Component, System, Group, Resource, Location, Template, API, User, Domain]
          locations:
            - target: https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml
              type: url
            - target: /opt/backstage/locations/users.yaml
              type: file
            - target: /opt/backstage/locations/workflow-resources.yaml
              type: file
          csp:
            script-src: ["'self'", "'unsafe-inline'", "'unsafe-eval'"]
            script-src-elem: ["'self'", "'unsafe-inline'", "'unsafe-eval'"]
            connect-src: ["'self'", 'http:', 'https:', 'data:']
        orchestrator:
          catalog:
            environment: development
