
apiVersion: v1
kind: Pod
metadata:
  name: ingestor
  labels:
    app: ingestor
spec:
  containers:
    - name: ingestor
      image: localhost/kubesmarts/akrivis-ingestor:1.0
      ports:
        - containerPort: 8083
      env:
        - name: DB_USERNAME
          value: "sarah"
        - name: DB_PASSWORD
          value: "connor"
        - name: DB_CONNECTION_STRING
          value: "jdbc:postgresql://postgres-db:5432/quarkus_test"
