
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=sarah
%dev.quarkus.datasource.password=connor
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_test

%dev.akrivis.evaluator.address=http://localhost:8082
%test.akrivis.evaluator.address=http://localhost:8081

%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_CONNECTION_STRING}
%prod.quarkus.datasource.jdbc.max-size=8
%prod.quarkus.datasource.jdbc.min-size=2
%prod.quarkus.hibernate-orm.database.generation=none

%prod.akrivis.evaluator.address=${EVALUATOR_ADDRESS}


